.github/auto_assign.yml
.github/workflows/auto-assign-action.yml

자동으로 self assign 이 될 수 있는 github action 추가해놓을게요~!!

Implement Github Action - Auto Self Assignee

---

.gitignore

git ignore 추가

---

.swiftlint.yml
attendance-ios/Source/BaseViewModel.swift
attendance-ios/Source/Model/Models.swift
attendance-ios/Source/SignUp/SignUpTeamInfoViewController.swift
attendance-ios/Source/SignUp/SignUpViewModel.swift

- 회원가입시 유저 정보 저장
- 회원가입시 필요한 모델들 수정
- 회원가입시 데이터 파이어베이스에 저장

회원가입시 유저 정보 저장

---

attendance-ios.xcodeproj/project.pbxproj
attendance-ios/Source/Model/Attendance.swift
attendance-ios/Source/Model/Models.swift
attendance-ios/Source/SignUp/SignUpTeamInfoViewController.swift
attendance-ios/Source/SignUp/SignUpViewModel.swift

- 4.7(목) 기준으로 파이어베이스 모델 변경사항 적용했습니다!

#37 파이어베이스 모델 변경사항 적용

---

attendance-ios.xcodeproj/project.pbxproj
attendance-ios/Source/BaseViewModel.swift
attendance-ios/Source/SignUp/SignUpViewModel.swift
attendance-ios/Source/Utilities/FirebaseWorker.swift
attendance-ios/Source/Utilities/KakaoLoginWorker.swift

- #46 파이어베이스 데이터 삭제 기능
- #48 로그인 화면: 이미 회원가입한 경우 홈으로 이동
- 파이어베이스 관리 클래스 구현
- 카카오 로그인 관리하는 클래스구현
- 이미 가입한 유저라면 바로 홈으로 이동

파이어베이스, 카카오톡 로그인 관리 클래스 구현, 데이터 삭제 기능 추가, 이미 가입한 유저인지 체크

---

attendance-ios.xcodeproj/project.pbxproj
attendance-ios/Resource/Assets.xcassets/icon/qr.imageset/Contents.json
attendance-ios/Source/Extensions/UIFont.swift
attendance-ios/Source/Extensions/UILabel.swift
attendance-ios/Source/Extensions/UIViewController.swift
attendance-ios/Source/Home/HomeBottomTabView.swift
attendance-ios/Source/Home/HomeViewController.swift
attendance-ios/Source/Home/HomeViewModel.swift
attendance-ios/Source/QR/QRViewController.swift
attendance-ios/Source/Setting/SettingCellView.swift
attendance-ios/Source/Setting/SettingViewController+UI.swift
attendance-ios/Source/Setting/SettingViewController.swift
attendance-ios/Source/Setting/SettingViewModel.swift

- 홈 레이아웃 오류 나는 부분 수정
- font 함수 이름을 style로 수정 (헷갈리지 않게 수정했습니다)
- font에서 semibold 에 이름 오류가 있어서 수정했습니다.
- setting UI 화면 추가했습니다.

#34 멤버용 - 설정 UI 구현 

---

attendance-ios/Source/Model/Attendance.swift

- 파이어베이스 관련 모델 수정
- Attendance의 type을 AttendanceType으로 설정하면, 파이어베이스 내의 문서를 가져올 때 디코딩이 되지 않아
- AttendanceData라는 타입을 만들었습니다
```
struct Attendance: Codable {
let sessionId: Int
let type: AttendanceData
}
struct AttendanceData: Codable {
let point: Int
let text: String
}
enum AttendanceType: Codable, CaseIterable {
case absence
case tardy
case attendance
case attendanceMarked
var text: String {
switch self {
case .attendance: return "출석"
case .tardy: return "지각"
case .absence: return "결석"
case .attendanceMarked: return "출석 인정"
}
}
var point: Int {
switch self {
case .attendance: return 0
case .tardy: return -10
case .absence: return -20
case .attendanceMarked: return 0
}
}
}
```

AttendanceType 모델 수정

---

attendance-ios/Resource/Info.plist

#76 다크모드 막음

---

attendance-ios/Source/Extensions/UIKit/UIViewController.swift
attendance-ios/Source/Home/HomeAttendanceCheckViewController.swift
attendance-ios/Source/Home/HomeTotalScoreTableViewCell.swift
attendance-ios/Source/Home/HomeViewController.swift
attendance-ios/Source/Home/HomeViewModel.swift
attendance-ios/Source/QR/QRViewController.swift
attendance-ios/Source/QR/QRViewModel.swift
attendance-ios/Source/Setting/SettingCellView.swift
attendance-ios/Source/Setting/SettingPrivacyPolicyViewController.swift

- 도움말 클릭 오류 수정
- 프로그레스바 수정
- 개인정보처리방침 노션 연결 (로딩 길어서 추후 수정 필요)
- 토스트 메시지 크기 수정
- QR 화면 시간 받아와서 수정
- 실패시 오류 문구

#36 개인정보처리방침 추가

---

attendance-ios.xcodeproj/project.pbxproj
attendance-ios/Source/Common/AlertView.swift
attendance-ios/Source/Common/BaseViewModel.swift
attendance-ios/Source/Login/EasterEggView.swift
attendance-ios/Source/Login/LoginViewController.swift

- #79 
- 부엉이 15번 누적 클릭 체크
-이스터 에그 화면 생성, 누적 클릭시 띄움
- 확인 클릭시 BaseViewModel에 입력한 비번 전달
- BaseViewModel에서 해당 비번이 유효한지 체크, 유효하다면 관리자용 화면으로 이동
| 로그인 화면 | 15번 누적 클릭시 창 띄움 | 키 입력 | 키가 유효할 경우 관리자용 화면으로 이동 |
| :-: | :-: | :-: | :-: |
| <img src="https://user-images.githubusercontent.com/61302874/168783804-b639ecf3-5e2e-4720-992a-166f3ae08964.PNG" > | <img src="https://user-images.githubusercontent.com/61302874/168783832-96d7fd64-3b9e-419c-87cb-a47e57e1440c.PNG" > | <img src="https://user-images.githubusercontent.com/61302874/168783853-9c1375d2-e2ed-4e3e-83ad-4009dd674d5b.PNG" > | <img src="https://user-images.githubusercontent.com/61302874/168783867-a78277c7-60f1-4ae0-94fe-9b5036e0cd40.PNG" > |

로그인 - 이스터 에그

---

attendance-ios/Source/Admin/Main/AdminSessionCell.swift
attendance-ios/Source/Admin/Main/AdminViewController.swift

- #88 
- 셀이 아닌 우측 버튼 클릭시 출결 화면으로 이동하도록 수정

#88 출결 화면 이동 셀 클릭 범위 수정

---

attendance-ios/Source/Admin/Management/AdminBottomSheetView.swift
attendance-ios/Source/Admin/Management/AdminManagementViewController.swift

#87 관리자용 - 하단 시트 애니메이션

---

attendance-ios/Source/Extensions/UIKit/UIViewController.swift
attendance-ios/Source/Setting/SettingViewController.swift
attendance-ios/Source/SignUp/SignUpNameViewController.swift
attendance-ios/Source/SignUp/SignUpPositionViewController.swift
attendance-ios/Source/SignUp/SignUpTeamViewController.swift

- #109 
- #112 
- #108
- 회원 가입에서 컬렉션뷰가 스크롤이 되지 않도록 수정
- 뒤로 가기 버튼 UIViewController extension으로 개선, 버튼 크기 키움
- 회원 가입에서 셀이 약간 잘리는 문제 해결

회원가입 UI 수정

---

attendance-ios/Source/Common/BaseViewModel.swift
attendance-ios/Source/Login/LoginViewController.swift

- #105 
- 로그인에 실패한 경우 실패 토스트 띄움
* 메세지: 로그인에 실패했습니다. 다시 시도해주세요.로 수정함

#105 로그인에 실패한 경우 실패 토스트 띄움

---

attendance-ios/Source/Common/BaseViewModel.swift
attendance-ios/Source/Home/HomeViewModel.swift
attendance-ios/Source/Login/LoginViewController.swift
attendance-ios/Source/Setting/SettingViewModel.swift
attendance-ios/Source/System/SceneDelegate.swift
attendance-ios/Source/Utilities/UserDefaultsWorker.swift

- #107
- 스플래시가 한번만 보이도록 설정
- UserDefaultsWorker 함수 네이밍 수정, UserDefaultsKey 모델 클래스 내부로 이동
- 스플래시 배경을 주황색으로 설정해야 하는데, WKWebView의 배경색을 설정할 수가 없어서
- loginSplashView를 처음 생성할 때나, webView(didFinish~)에서 아래의 코드들을 실행해도 
- 배경색이 투명해지지가 않아서(기본 배경색이 투명이라고 하는데, 왜 흰색으로 보이는 지 모르겠습니다ㅜ)
- 현재는 스플래시 배경색을 흰색으로 처리한 상태입니다..!
- 로그인 스플래시를 배경이 처리된 파일로 띄우는 방법도 있을 것 같은데,
- 일단 스플래시 배경색 관련 이슈는 새로 생성하겠습니다
```
loginSplashView.isOpaque = false
loginSplashView.backgroundColor = UIColor.clear
loginSplashView.scrollView.backgroundColor = UIColor.clear
loginSplashView.layer?.backgroundColor = UIColor.clear.cgColor
```

#107 로그인 - 자동 로그인일 때 스플래시 화면 표시

---

attendance-ios/Source/Admin/Main/AdminViewController.swift
attendance-ios/Source/Extensions/UIKit/UIViewController.swift
attendance-ios/Source/Home/HelpViewController.swift
attendance-ios/Source/Home/HomeAttendanceDetailViewController.swift
attendance-ios/Source/Setting/SettingViewController+UI.swift

- #101 
- 네비게이션바 height 수정 필요(전체적으로 맞추기)
- 관리자용 화면에서 로그아웃 버튼 extension으로 수정
| 1 | 2 | 3 |
| :-: | :-: | :-: |
| <img src="https://user-images.githubusercontent.com/61302874/169459952-dab72aa5-9381-47b0-a080-0ab082a9eb6a.PNG" > | <img src="https://user-images.githubusercontent.com/61302874/169459979-861384db-0235-4653-8d1e-9a2274a5a5aa.PNG" > | <img src="https://user-images.githubusercontent.com/61302874/169459991-2feea353-8427-4015-961c-520d9c697d32.PNG" > |

#101 네비게이션바 height 수정

---

attendance-ios/Source/Utilities/FirebaseWorker.swift

#74 관리자용 - 출결 변경시 문서 업데이트 안되는 문제 해결

---

attendance-ios/Source/Login/LoginViewController.swift
attendance-ios/Source/SignUp/SignUpNameViewController.swift
attendance-ios/Source/SignUp/SignUpPositionViewController.swift
attendance-ios/Source/SignUp/SignUpTeamViewController.swift

#124 뒤로가기 버튼 클릭 잘 안되는 부분 수정

---

attendance-ios/Source/Extensions/UIKit/UILabel.swift
attendance-ios/Source/Home/HelpViewController.swift

- #100
- 도움말 읽어보세요 문구 텍스트 부분 bold 처리
- 도움말 읽어보세요 문구 leading 맞추도록 수정

#100 점수화면 - 도움말 UI 수정 필요

---

attendance-ios/Source/Admin/Grade/AdminGradeViewController.swift
attendance-ios/Source/Admin/Main/AdminViewController.swift
attendance-ios/Source/Admin/Management/AdminManagementViewController.swift
attendance-ios/Source/Common/View/BaseNavigationBarView.swift
attendance-ios/Source/Extensions/UIKit/UIViewController.swift
attendance-ios/Source/Home/HelpViewController.swift
attendance-ios/Source/Home/HomeAttendanceCheckViewController.swift
attendance-ios/Source/Setting/SettingPrivacyPolicyViewController.swift
attendance-ios/Source/Setting/SettingViewController.swift

- #97 
- 도움말, 설정, 관리자 화면에 스와이프 뒤로가기 추가
- 네비게이션 바 수정

#97 스와이프 뒤로가기, 네비게이션바 수정

---

attendance-ios/Source/Admin/Main/AdminTodayView.swift
attendance-ios/Source/Admin/Main/AdminViewController.swift

#132 오늘 세션의 관리 버튼이 안눌리는 문제 해결

---

attendance-ios/Source/Extensions/UIKit/UIViewController.swift

- #134
- 회원 가입에서 네비게이션 바 배경색상을 지웠습니다 !

#134 뒤로가기 클릭시 네비게이션바 배경색상이 보이는 문제 해결

---

attendance-ios/Source/Login/LoginViewController.swift

#130 다시 로그인 진입시 스플래시의 주황 배경이 잠깐 보이는 문제 해결

---

attendance-ios/Source/Home/HomeViewController.swift

#99 모든 세션을 끝마쳤습니다 표시

---

attendance-ios/Source/Common/BaseViewModel.swift
attendance-ios/Source/Login/LoginViewController.swift
attendance-ios/Source/Setting/SettingViewModel.swift
attendance-ios/Source/Utilities/FirebaseWorker.swift
attendance-ios/Source/Utilities/UserDefaultsWorker.swift

- #142 
- #143 
- #145 
- #146

애플 로그인 및 회원가입 세션 수정

---

attendance-ios/Source/Admin/Main/AdminSessionCell.swift

#158 관리자 셀이 재활용될 때 관찰하던 버튼 세팅

---

attendance-ios/Source/Login/LoginViewController.swift

#141 돌아왔을 때 스플래시가 보이도록 수정

---

attendance-ios/Source/Extensions/UIKit/UIViewController.swift
attendance-ios/Source/Home/HomeAttendanceCheckTableViewCell.swift
attendance-ios/Source/Home/HomeAttendanceCheckViewController.swift
attendance-ios/Source/Home/HomeTotalScoreTableViewCell.swift
attendance-ios/Source/Setting/SettingViewController+UI.swift

- 설정 > 버튼 크기 논의 필요
- 출결확인 라인 색상 안보이는 부분 논의 필요
- 출결확인 프로그래스바 반원 눌리는 부분 확인 필요

#153, #154 홈 UI 수정

---

attendance-ios/Source/Admin/Main/AdminViewController.swift

#156 오늘 세션 출결 관리 터치 관련 버튼 설정

---

attendance-ios/Source/Common/View/BaseNavigationBarView.swift

- #177 세션 제목이 긴 경우 화면을 넘어가는 문제 해결

#177 세션 제목이 긴 경우 화면을 넘어가는 문제 해결

---

attendance-ios/Source/Setting/SettingViewModel.swift

#181 유저 정보가 없는 경우 홈으로 이동

---

attendance-ios/Source/Common/BaseViewModel.swift

- #188 애플 로그인시 홈화면이 두번 넘어가는 문제 해결

#188 애플 로그인시 홈화면이 두번 넘어가는 문제 해결

---

attendance-ios/Source/Login/LoginViewController.swift

스플래시 화면 수정
